from typing import Protocol, Any, Optional
from .models.order import OrderIntent

class ExchangePort(Protocol):
    async def place_bracket(self, intent: OrderIntent) -> Any: ...
    async def close_market(self, market: str, side: str, base_amount: str) -> Any: ...
    async def cancel_all(self, market: Optional[str] = None) -> Any: ...
    async def list_open_orders(self, market: Optional[str] = None) -> list[dict]: ...
